# Generated by Django 5.2.4 on 2025-07-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_remove_booking_is_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First Seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last Seen')),
                ('booking_count', models.IntegerField(default=0, verbose_name='Booking Count')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Is Blocked')),
                ('block_reason', models.CharField(blank=True, max_length=255, verbose_name='Block Reason')),
            ],
            options={
                'verbose_name': 'IP Tracker',
                'verbose_name_plural': 'IP Trackers',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='SpamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('attempt_type', models.CharField(choices=[('rate_limit', 'Rate Limited'), ('duplicate', 'Duplicate Booking'), ('honeypot', 'Honeypot Triggered'), ('suspicious', 'Suspicious Activity')], max_length=50, verbose_name='Attempt Type')),
                ('details', models.TextField(blank=True, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Spam Log',
                'verbose_name_plural': 'Spam Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_suspicious',
            field=models.BooleanField(default=False, verbose_name='Suspicious Activity'),
        ),
        migrations.AddField(
            model_name='booking',
            name='spam_score',
            field=models.IntegerField(default=0, verbose_name='Spam Score'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
    ]
