# Generated by Django 5.2.4 on 2025-08-14 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_iptracker_spamlog_booking_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked Date')),
                ('is_holiday', models.BooleanField(default=False, verbose_name='Holiday')),
                ('is_maintenance', models.BooleanField(default=False, verbose_name='Maintenance Day')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Studio Schedule',
                'verbose_name_plural': 'Studio Schedules',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.CharField(choices=[('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM')], max_length=5, verbose_name='Time')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Booked')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.booking', verbose_name='Booking')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['date', 'time'],
                'unique_together': {('date', 'time')},
            },
        ),
    ]
