# Generated by Django 5.2.4 on 2025-08-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_studioschedule_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Confirmation Token'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='Email Sent'),
        ),
        migrations.AddField(
            model_name='booking',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email Sent At'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_token',
            field=models.CharField(blank=True, max_length=100, verbose_name='Rejection Token'),
        ),
    ]
