# Generated by Django 5.2.4 on 2025-08-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_confirmation_token_booking_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.CharField(choices=[('recording', 'Recording'), ('mixing', 'Mixing'), ('mastering', 'Mastering'), ('production', 'Music Production'), ('vocal_cleanup', 'Vocal Cleanup'), ('vocal_tuning', 'Vocal Tuning'), ('hourly', 'Hourly Rate'), ('daily', 'Daily Rental')], max_length=20, verbose_name='Service'),
        ),
    ]
