# Generated by Django 5.2.4 on 2025-08-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_description', models.CharField(blank=True, max_length=300)),
                ('default_keywords', models.CharField(blank=True, max_length=500)),
                ('og_image_url', models.URLField(blank=True)),
                ('google_site_verification', models.CharField(blank=True, max_length=200)),
                ('bing_site_verification', models.CharField(blank=True, max_length=200)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('telegram_url', models.URLField(blank=True)),
                ('tiktok_url', models.URLField(blank=True)),
                ('gtag_enabled', models.BooleanField(default=False)),
                ('ga4_measurement_id', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Абсолютный путь, например /en/services/ или шаблон /services/', max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uk', 'Ukrainian'), ('de', 'German')], max_length=5)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=200)),
                ('og_description', models.CharField(blank=True, max_length=300)),
                ('og_image_url', models.URLField(blank=True)),
                ('canonical_override', models.URLField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['path', 'language'], name='booking_pag_path_4de972_idx')],
                'unique_together': {('path', 'language')},
            },
        ),
    ]
